import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { signToken, logAdminAction } from '@/lib/auth';
import { markBotConnected } from '@/lib/bot-auth';

/**
 * Bot Pairing Authentication
 * POST /api/auth/bot-pair
 * Body: { pairingCode: string, botNumber?: string }
 *
 * Authenticates a bot using a pairing code generated by the admin.
 * On success, returns an admin JWT token that the bot can use for all API calls.
 * The pairing code is consumed (deleted) after successful authentication.
 * Bot is marked as "connected" in the system.
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const pairingCode = (body.pairingCode || '').toString().trim().toUpperCase();
    const botNumber = (body.botNumber || '').toString().trim();

    if (!pairingCode) {
      return NextResponse.json(
        { success: false, error: 'Pairing code is required' },
        { status: 400 }
      );
    }

    // Find admin with this pairing code
    const admin = await db.admin.findFirst({
      where: { pairingCode },
    });

    if (!admin) {
      return NextResponse.json(
        { success: false, error: 'Invalid pairing code' },
        { status: 401 }
      );
    }

    // Check if pairing code has expired
    if (!admin.pairingCodeExpiry || new Date() > admin.pairingCodeExpiry) {
      // Clean up expired code
      await db.admin.update({
        where: { id: admin.id },
        data: { pairingCode: null, pairingCodeExpiry: null },
      });
      return NextResponse.json(
        { success: false, error: 'Pairing code has expired. Please generate a new one.' },
        { status: 401 }
      );
    }

    // Check admin role
    if (admin.role !== 'admin' && admin.role !== 'super_admin') {
      return NextResponse.json(
        { success: false, error: 'Access denied. Invalid admin role.' },
        { status: 403 }
      );
    }

    // Consume the pairing code (one-time use for security)
    await db.admin.update({
      where: { id: admin.id },
      data: {
        pairingCode: null,
        pairingCodeExpiry: null,
        lastLogin: new Date(),
        loginAttempts: 0,
        lockedUntil: null,
      },
    });

    // Mark bot as connected in SystemSettings
    await markBotConnected(botNumber || undefined);

    // Log the pairing authentication
    await logAdminAction(admin.id, 'BOT_PAIRED', `Bot authenticated via pairing code${botNumber ? ` (bot: ${botNumber})` : ''}`);

    // Generate admin JWT token for the bot
    const token = signToken({
      userId: admin.id,
      type: 'admin',
      role: admin.role,
    });

    return NextResponse.json({
      success: true,
      data: {
        token,
        admin: {
          id: admin.id,
          username: admin.username,
          email: admin.email,
          name: admin.name,
          role: admin.role,
        },
        message: 'Bot paired successfully! Use the token for API authentication. Bot is now connected.',
      },
    });
  } catch (error) {
    console.error('Bot pair auth error:', error);
    return NextResponse.json(
      { success: false, error: 'Server error' },
      { status: 500 }
    );
  }
}
