/**
 * Auto-create .env file with DATABASE_URL if it doesn't exist.
 *
 * Why this exists:
 *   - `.env` is gitignored (correct — never commit secrets).
 *   - On a fresh VPS deploy (`git clone`), there is NO `.env` file.
 *   - Without `DATABASE_URL`, `prisma db push` fails with:
 *       "Environment variable not found: DATABASE_URL" (P1012)
 *   - This script auto-creates `.env` with a working SQLite path so
 *     `prisma db push`, `prisma generate`, and the Next.js runtime
 *     all work out-of-the-box on any machine / VPS.
 *
 * Runs automatically via npm/bun scripts:
 *   - postinstall  (after `bun install`)
 *   - db:push      (before `prisma db push`)
 *   - db:generate  (before `prisma generate`)
 *
 * Safe to run multiple times — it only creates .env if missing.
 * If .env already exists, it does nothing (preserves user edits).
 */
import fs from 'fs';
import path from 'path';

const cwd = process.cwd();
const envPath = path.resolve(cwd, '.env');

// Already exists? Leave it alone (user may have customized it).
if (fs.existsSync(envPath)) {
  // Make sure it actually contains DATABASE_URL; if not, append it.
  const existing = fs.readFileSync(envPath, 'utf8');
  if (/^\s*DATABASE_URL\s*=/m.test(existing)) {
    console.log('[setup-env] .env already exists with DATABASE_URL — keeping as-is.');
    process.exit(0);
  }
  // Append DATABASE_URL to the existing .env
  const dbPath = path.resolve(cwd, 'db', 'custom.db');
  fs.mkdirSync(path.dirname(dbPath), { recursive: true });
  const append = `\n# Auto-added by scripts/setup-env.mjs\nDATABASE_URL="file:${dbPath}"\n`;
  fs.appendFileSync(envPath, append);
  console.log(`[setup-env] Appended DATABASE_URL to existing .env → file:${dbPath}`);
  process.exit(0);
}

// No .env at all → create one with a sensible default SQLite path.
const dbPath = path.resolve(cwd, 'db', 'custom.db');
fs.mkdirSync(path.dirname(dbPath), { recursive: true });

const envContent = `# Auto-generated by scripts/setup-env.mjs
# Do NOT commit this file (.env is gitignored).
# SQLite database path (absolute, so prisma CLI + Next.js runtime agree).
DATABASE_URL="file:${dbPath}"
`;

fs.writeFileSync(envPath, envContent, { mode: 0o644 });
console.log(`[setup-env] Created .env with DATABASE_URL="file:${dbPath}"`);
